"""Initial migration

Revision ID: 69dac6825d58
Revises:
Create Date: 2024-11-05 14:47:27.062195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision: str = '69dac6825d58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steam_games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('categories', sa.String(), nullable=True),
    sa.Column('user_reviews', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('developer', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('combined_text', sa.String(), nullable=True),
    sa.Column('embedding', Vector(dim=384), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steam_games_developer'), 'steam_games', ['developer'], unique=False)
    op.create_index('ix_steam_games_embedding', 'steam_games', ['embedding'], unique=False, postgresql_using='ivfflat')
    op.create_index(op.f('ix_steam_games_name'), 'steam_games', ['name'], unique=False)
    op.create_index(op.f('ix_steam_games_publisher'), 'steam_games', ['publisher'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_steam_games_publisher'), table_name='steam_games')
    op.drop_index(op.f('ix_steam_games_name'), table_name='steam_games')
    op.drop_index('ix_steam_games_embedding', table_name='steam_games', postgresql_using='ivfflat')
    op.drop_index(op.f('ix_steam_games_developer'), table_name='steam_games')
    op.drop_table('steam_games')
    # ### end Alembic commands ###
