"""New api_setup Table

Revision ID: 9dd1751dc611
Revises: 69dac6825d58
Create Date: 2024-11-05 18:53:25.209007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd1751dc611'
down_revision: Union[str, None] = '69dac6825d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_setup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_setup_model'), 'api_setup', ['model'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_setup_model'), table_name='api_setup')
    op.drop_table('api_setup')
    # ### end Alembic commands ###
