"""Update api_setup Table

Revision ID: d7a4c8618b78
Revises: 9dd1751dc611
Create Date: 2024-11-05 23:44:40.240362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7a4c8618b78'
down_revision: Union[str, None] = '9dd1751dc611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_setup', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_setup', 'active')
    # ### end Alembic commands ###
